export default {
  test: {
    environment: 'node',
    include: [
      'src/**/*.{test,spec}.{js,jsx}',
      'scripts/**/*.{test,spec}.{js,mjs}',
      'netlify/functions/**/*.{test,spec}.js',
    ],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json-summary'],
      reportsDirectory: 'coverage/h1',
      all: true,
      include: [
        'src/app/**/*.{js,jsx}',
        'src/design-system/**/*.{js,jsx}',
        'src/home/**/*.{js,jsx}',
        'src/tournament/**/*.{js,jsx}',
        'src/auth/**/*.{js,jsx}',
        'src/guest/**/*.{js,jsx}',
        'src/predictions/**/*.{js,jsx}',
        'src/journey/**/*.{js,jsx}',
        'src/koPredictor/**/*.{js,jsx}',
        'src/grace/**/*.{js,jsx}',
        'src/results/**/*.{js,jsx}',
        'src/matchCentre/**/*.{js,jsx}',
        'src/bracketHealth/**/*.{js,jsx}',
        'src/player/**/*.{js,jsx}',
        'src/teamProfile/**/*.{js,jsx}',
        'src/observability/**/*.{js,jsx}',
        'src/admin/**/*.{js,jsx}',
        'src/leagues/**/*.{js,jsx}',
        'src/runtime/**/*.{js,jsx}',
        'src/resolver/**/*.{js,jsx}',
        'src/config/**/*.{js,jsx}',
        'src/contracts/**/*.{js,jsx}',
        'src/lib/**/*.{js,jsx}',
      ],
      exclude: [
        'src/**/*.test.{js,jsx}',
        'src/**/__tests__/**',
        'src/testFixtures/**',
        'src/pages/**',
        'src/components/**',
        'src/store/**',
        'src/assets/**',
        'src/**/*.module.css',
      ],
    },
  },
}
